### ISSUE TITLE
Missing support for import

### ISSUE THREAD

**Issue by ChristianChoi** [hectorj/terraform-provider-googlesiteverification#3]
Hi there,

First of all I'd like to thank you for making this Terraform provider plugin. I've been looking for one for some time.

Are you planning on adding support for importing existing resources? If not, then I can write a PR for it once I get some time.

**Comment by hectorj** [comment]
>Hi there,
>
>First of all I'd like to thank you for making this Terraform provider plugin. I've been looking for one for some time.

Hi!

I am verry happy to hear that it is useful to someone.

> Are you planning on adding support for importing existing resources? If not, then I can write a PR for it once I get some time.

May I ask what is the use case? Currently if your user is already verified, an API call will be made but it should not fail, it should just be a no-op.

Anyway, done with https://github.com/hectorj/terraform-provider-googlesiteverification/pull/4, released with v0.3.0.

Do not hesitate if you have more needs this provider may satisfy 🙂

**Comment by ChristianChoi** [comment]
Hi,

Quick response, awesome!

> May I ask what is the use case? Currently if your user is already verified, an API call will be made but it should not fail, it should just be a no-op.

I have a module that creates DNS records for a domain, and so far I've manually been creating the domain in Google Site Verification, copied the TXT record value and passed it to the module via variables. With your provider plugin I'm trying to automate this process completely.

My experience with other resources that already exists, is that the provider will attempt to create the resource again **and fail**, resulting in me having to use `terraform import` anyway. So honestly I actually didn't even try to run `terraform apply` after adding `resource "googlesiteverification_dns" "my_domain" { domain = "mydomain.com"}` to my TF file, as I didn't expect it would work since the resource already exists in Google Site Verification.

**Comment by ChristianChoi** [comment]
So out of curiosity I decided to try see what would happen if I tried to create a resource that already exists:
```
provider "googlesiteverification" {
  credentials = file(var.gcloud_json_file)
}

resource "googlesiteverification_dns" "test" {
  domain = "my_domain.com"
}
```

```
$ terraform plan -out=test
...
...
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # googlesiteverification_dns.test will be created
  + resource "googlesiteverification_dns" "test" {
      + domain = "my_domain.com"
      + id     = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

```
$ terraform apply test
googlesiteverification_dns.test: Creating...
googlesiteverification_dns.test: Still creating... [10s elapsed]
googlesiteverification_dns.test: Still creating... [20s elapsed]
googlesiteverification_dns.test: Still creating... [30s elapsed]
googlesiteverification_dns.test: Still creating... [40s elapsed]
googlesiteverification_dns.test: Still creating... [50s elapsed]
googlesiteverification_dns.test: Still creating... [1m0s elapsed]
googlesiteverification_dns.test: Still creating... [1m10s elapsed]
googlesiteverification_dns.test: Still creating... [1m20s elapsed]
googlesiteverification_dns.test: Still creating... [1m30s elapsed]
googlesiteverification_dns.test: Still creating... [1m40s elapsed]
googlesiteverification_dns.test: Still creating... [1m50s elapsed]
googlesiteverification_dns.test: Still creating... [2m0s elapsed]
googlesiteverification_dns.test: Still creating... [2m10s elapsed]
googlesiteverification_dns.test: Still creating... [2m20s elapsed]
googlesiteverification_dns.test: Still creating... [2m30s elapsed]
googlesiteverification_dns.test: Still creating... [2m40s elapsed]
googlesiteverification_dns.test: Still creating... [2m50s elapsed]
googlesiteverification_dns.test: Still creating... [3m0s elapsed]
googlesiteverification_dns.test: Still creating... [3m10s elapsed]
googlesiteverification_dns.test: Still creating... [3m20s elapsed]
googlesiteverification_dns.test: Still creating... [3m30s elapsed]
googlesiteverification_dns.test: Still creating... [3m40s elapsed]
googlesiteverification_dns.test: Still creating... [3m50s elapsed]
googlesiteverification_dns.test: Still creating... [4m0s elapsed]
googlesiteverification_dns.test: Still creating... [4m10s elapsed]
googlesiteverification_dns.test: Still creating... [4m20s elapsed]
googlesiteverification_dns.test: Still creating... [4m30s elapsed]
googlesiteverification_dns.test: Still creating... [4m40s elapsed]
googlesiteverification_dns.test: Still creating... [4m50s elapsed]
googlesiteverification_dns.test: Still creating... [5m0s elapsed]
googlesiteverification_dns.test: Still creating... [5m10s elapsed]
googlesiteverification_dns.test: Still creating... [5m20s elapsed]
googlesiteverification_dns.test: Still creating... [5m30s elapsed]
googlesiteverification_dns.test: Still creating... [5m40s elapsed]
googlesiteverification_dns.test: Still creating... [5m50s elapsed]
googlesiteverification_dns.test: Still creating... [6m0s elapsed]
googlesiteverification_dns.test: Still creating... [6m10s elapsed]
googlesiteverification_dns.test: Still creating... [6m20s elapsed]
googlesiteverification_dns.test: Still creating... [6m30s elapsed]
(and it's still going)
```

So while it doesn't seem to fail, it doesn't seem to finish either 😅 
I'll try your newly added importer instead 😉

**Comment by ChristianChoi** [comment]
Oh I just realised that create-resource is actually just to verify the domain. Now it all makes sense! What I actually need is to use your `dns_token` resource for https://developers.google.com/site-verification/v1/webResource/getToken instead.

I'm sorry for the confusion.

**Comment by hectorj** [comment]
No problem, I'm really enjoying this project having at least 1 potential user.

The importer might be useful later if I implement other parts of the API (for now this is really the strict minimum I needed for my own usage).

**Comment by ChristianChoi** [comment]
`googlesiteverification_dns_token` was definitely the right resource to use. However I'm authorizing using GCP service account, which make the service account the owner of the Site Verification property, and therefore I don't see it on https://search.google.com/search-console because it's authorizing using google account email.

So it turns out I actually need to be able to use https://developers.google.com/site-verification/v1/webResource/update to update owners, and not the ability to import existing `googlesiteverification_dns` resource to TF state... 🤦‍♂️

**Comment by hectorj** [comment]
I see 😄 

Here is a new issue to track it: https://github.com/hectorj/terraform-provider-googlesiteverification/issues/6
