### ISSUE TITLE
when the  googlesiteverification_dns resource is deleted, ownership is still registered

### ISSUE THREAD

**Issue by mvanholsteijn** [hectorj/terraform-provider-googlesiteverification#9]
When you  create a googlesiteverification_dns, your identity is registered as owner of the domain. When you delete it  the identity  is still registered as owner.

When you use the Web interface to  remove  the ownership registration, it is properly deleted. The log shows the following message:
```
The verification record was deleted by ...
```
the code shows a Noop for  the  delete, could we replace it with a https://developers.google.com/site-verification/v1/webResource/delete ?

**Comment by hectorj** [comment]
Hi!

I have a small problem to implement this:

We can't delete the ownership before the DNS record is deleted. That makes no sense to me, but the API gives this error: 
`Error 400: You cannot unverify your ownership of this site until your verification token (meta tag, HTML file, Google Analytics tracking code, Google Tag Manager container code, or DNS record) has been removed.`

And I don't know how to tell this to Terraform.

That resource needs to be both created and deleted after the DNS record, and a `depends_on` can only force one of those...

**Comment by mvanholsteijn** [comment]
I actually implemented this by doing a retry  on  the delete operation.  Check out  https://github.com/hectorj/terraform-provider-googlesiteverification/compare/master...binxio:issue-9

the branch also contains a fix for the token dependency.

**Comment by hectorj** [comment]
Your changes look good. May I merge them in this repo?

(sorry for the long delay)

**Comment by mvanholsteijn** [comment]
Sure! Go ahead!

**Comment by hectorj** [comment]
Fixed by #11 , thank you
